/*
 * Copyright 2007 Andrew De Ponte
 *
 * This file is part of lib_sxs.
 *
 * lib_sxs is the intellectual property of Andrew De Ponte; any
 * distribution and/or modifications and/or reproductions of any portion
 * of lib_sxs MUST be approved by Andrew De Ponte.
 *
 * lib_sxs is dirstributed WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE.
 */

/**
 * @file sxs_error.h
 * @brief This is a specifications file for error hanlding in lib_sxs.
 *
 * The sxs_error.h file is a specifications file that defines the types
 * which represent errors and all their possible values, as well as
 * providing prototypes for error handling functions.
 */

 /* NOTE: This file is automatically generated and should never be
  * altered by hand. To make changes to this file please alter the
  * scripts/build_sxs_error_files.py script or any of it's associated
  * input files. */

#ifndef SXS_ERROR_H
#define SXS_ERROR_H

#include "sxs_types.h"

#define SXS_SUCCESS 0 /**< Operation completed successfully */
#define SXS_UNKNOWN_ERROR 0xffffffff /**< An undefined error occured */

/* The following are errors which are shared between both Unix varients
 * such as linux and mac as well as Windows. */
#define SXS_UNIXWIN_ERR_START 1
#define SXS_UNIXWIN_ERR_END 333
#define SXS_EINTR 1 /**< Interrupted system call */
#define SXS_EBADF 2 /**< Bad file number */
#define SXS_EACCES 3 /**< Permission denied */
#define SXS_EFAULT 4 /**< Bad address */
#define SXS_EINVAL 5 /**< Invalid argument */
#define SXS_EMFILE 6 /**< Too many open files */
#define SXS_EWOULDBLOCK 7 /**< Operation would block */
#define SXS_EINPROGRESS 8 /**< Operation now in progress */
#define SXS_EALREADY 9 /**< Operation already in progress */
#define SXS_ENOTSOCK 10 /**< Socket operation on non-socket */
#define SXS_EDESTADDRREQ 11 /**< Destination address required */
#define SXS_EMSGSIZE 12 /**< Message too long */
#define SXS_EPROTOTYPE 13 /**< Protocol wrong type for socket */
#define SXS_ENOPROTOOPT 14 /**< Protocol not available */
#define SXS_EPROTONOSUPPORT 15 /**< Protocol not supported */
#define SXS_ESOCKTNOSUPPORT 16 /**< Socket type not supported */
#define SXS_EOPNOTSUPP 17 /**< Operation not supported on transport endpoint */
#define SXS_EPFNOSUPPORT 18 /**< Protocol family not supported */
#define SXS_EAFNOSUPPORT 19 /**< Address family not supported by protocol */
#define SXS_EADDRINUSE 20 /**< Address already in use */
#define SXS_EADDRNOTAVAIL 21 /**< Cannot assign requested address */
#define SXS_ENETDOWN 22 /**< Network is down */
#define SXS_ENETUNREACH 23 /**< Network is unreachable */
#define SXS_ENETRESET 24 /**< Network dropped connection because of reset */
#define SXS_ECONNABORTED 25 /**< Software caused connection abort */
#define SXS_ECONNRESET 26 /**< Connection reset by peer */
#define SXS_ENOBUFS 27 /**< No buffer space available */
#define SXS_EISCONN 28 /**< Transport endpoint is already connected */
#define SXS_ENOTCONN 29 /**< Transport endpoint is not connected */
#define SXS_ESHUTDOWN 30 /**< Cannot send after transport endpoint shutdown */
#define SXS_ETOOMANYREFS 31 /**< Too mayn references: cannot splice */
#define SXS_ETIMEDOUT 32 /**< Connection timed out */
#define SXS_ECONNREFUSED 33 /**< Connection refused */
#define SXS_ELOOP 34 /**< Too many symbolic links encountered */
#define SXS_ENAMETOOLONG 35 /**< File name too long */
#define SXS_EHOSTDOWN 36 /**< Host is down */
#define SXS_EHOSTUNREACH 37 /**< No route to host */
#define SXS_ENOTEMPTY 38 /**< Directory not empty */
#define SXS_EUSERS 39 /**< Too many users */
#define SXS_EDQUOT 40 /**< Quota exceeded */
#define SXS_ESTALE 41 /**< Stale NFS file handle */
#define SXS_EREMOTE 42 /**< Remote I/O error */
#define SXS_UNIXBOTH_ERRMAP_SIZE 42
#ifdef WIN32
extern sxs_int32_t sxs_winboth_errmap[SXS_UNIXBOTH_ERRMAP_SIZE];
#else
extern sxs_int32_t sxs_unixboth_errmap[SXS_UNIXBOTH_ERRMAP_SIZE];
#endif


#define SXS_WIN_ERR_START 334
#define SXS_WIN_ERR_END 667
#define SXS_WSA_INVALID_HANDLE 334 /**< Event object handle is invalid */
#define SXS_WSA_NOT_ENOUGH_MEMORY 335 /**< Insufficient memory available */
#define SXS_WSA_INVALID_PARAMETER 336 /**< One or more params are invalid */
#define SXS_WSA_OPERATION_ABORTED 337 /**< Overlapped operation aborted */
#define SXS_WSA_IO_INCOMPLETE 338 /**< Overlapped I/O event object not in signaled state */
#define SXS_WSA_IO_PENDING 339 /**< Overlapped operations will complete later */
#define SXS_WSAEPROCLIM 340 /**< Too many processes */
#define SXS_WSASYSNOTREADY 341 /**< Network subsystem unavailable */
#define SXS_WSAVERNOTSUPPORTED 342 /**< Winsock.dll version out of range */
#define SXS_WSANOTINITIALISED 343 /**< Successful WSAStartup not yet performed */
#define SXS_WSAEDISCON 344 /**< Graceful shutdown in progress */
#define SXS_WSAENOMORE 345 /**< No more results */
#define SXS_WSAEINVALIDPROCTABLE 346 /**< Procedure call table is invalid */
#define SXS_WSAEINVALIDPROVIDER 347 /**< Service provider is invalid */
#define SXS_WSAEPROVIDERFAILEDINIT 348 /**< Service provider failed init */
#define SXS_WSASYSCALLFAILURE 349 /**< System call failure */
#define SXS_WSASERVICE_NOT_FOUND 350 /**< Service not found */
#define SXS_WSATYPE_NOT_FOUND 351 /**< Class type not found */
#define SXS_WSA_E_NO_MORE 352 /**< No more results */
#define SXS_WSA_E_CANCELLED 353 /**< Call was canceled */
#define SXS_WSAEREFUSED 354 /**< Database query was refused */
#define SXS_WSAHOST_NOT_FOUND 355 /**< Host not found */
#define SXS_WSATRY_AGAIN 356 /**< Nonauthoritative host not found */
#define SXS_WSANO_RECOVERY 357 /**< This is a nonrecoverable error */
#define SXS_WSANO_DATA 358 /**< Valid name, no data record */
#define SXS_WSA_QOS_RECEIVERS 359 /**< QOS receivers */
#define SXS_WSA_QOS_SENDERS 360 /**< QOS senders */
#define SXS_WSA_QOS_NO_SENDERS 361 /**< No QOS senders */
#define SXS_WSA_QOS_NO_RECEIVERS 362 /**< No QOS receivers */
#define SXS_WSA_QOS_REQUEST_CONFIRMED 363 /**< QOS request confirmed */
#define SXS_WSA_QOS_ADMISSION_FAILURE 364 /**< QOS admission error */
#define SXS_WSA_QOS_POLICY_FAILURE 365 /**< QOS policy failure */
#define SXS_WSA_QOS_BAD_STYLE 366 /**< QOS bad style */
#define SXS_WSA_QOS_BAD_OBJECT 367 /**< QOS bad object */
#define SXS_WSA_QOS_TRAFFIC_CTRL_ERROR 368 /**< QOS traffic control error */
#define SXS_WSA_QOS_GENERIC_ERROR 369 /**< QOS generic error */
#define SXS_WSAECANCELLED 370 /**< Operation Canceled */
#define SXS_WIN_ERRMAP_SIZE 37
#ifdef WIN32
extern sxs_int32_t sxs_win_errmap[SXS_WIN_ERRMAP_SIZE];
#endif

#define SXS_UNIX_ERR_START 668
#define SXS_UNIX_ERR_END 1000
#define SXS_ECHRNG 668 /**< Channel number out of range */
#define SXS_EL2NSYNC 669 /**< Level 2 not synchronized */
#define SXS_EL3HLT 670 /**< Level 3 halted */
#define SXS_EL3RST 671 /**< Level 3 reset */
#define SXS_ELNRNG 672 /**< Link number out of range */
#define SXS_EUNATCH 673 /**< Protocol driver not attached */
#define SXS_ENOCSI 674 /**< No CSI structure available */
#define SXS_EL2HLT 675 /**< Level 2 halted */
#define SXS_EBADE 676 /**< Invalid exchange */
#define SXS_EBADR 677 /**< Invalid request descriptor */
#define SXS_EXFULL 678 /**< Exchange full */
#define SXS_ENOANO 679 /**< No anode */
#define SXS_EBADRQC 680 /**< Invalid request code */
#define SXS_EBADSLT 681 /**< Invalid slot */
#define SXS_EBFONT 682 /**< Bad font file format */
#define SXS_ENONET 683 /**< Machine is not on the network */
#define SXS_ENOPKG 684 /**< Package not installed */
#define SXS_EADV 685 /**< Advertise error */
#define SXS_ESRMNT 686 /**< Srmount error */
#define SXS_ECOMM 687 /**< Communication error on send */
#define SXS_EDOTDOT 688 /**< RFS specific error */
#define SXS_ENOTUNIQ 689 /**< Name not unique on network */
#define SXS_EBADFD 690 /**< File descriptor in bad state */
#define SXS_EREMCHG 691 /**< Remote address changed */
#define SXS_ELIBACC 692 /**< Can not access a needed shared library */
#define SXS_ELIBBAD 693 /**< Accessing a corrupted shared library */
#define SXS_ELIBSCN 694 /**< .lib section in a.out corrupted */
#define SXS_ELIBMAX 695 /**< Attempting to link to too many shared libraries */
#define SXS_ELIBEXEC 696 /**< Cannot exec a shared library directly */
#define SXS_ERESTART 697 /**< Interrupted system call should be restarted */
#define SXS_ESTRPIPE 698 /**< Streams pipe error */
#define SXS_EUCLEAN 699 /**< Structure needs cleaning */
#define SXS_ENOTNAM 700 /**< Not a XENIX named type file */
#define SXS_ENAVAIL 701 /**< No XENIX semaphores available */
#define SXS_EISNAM 702 /**< Is a named type file */
#define SXS_EREMOTEIO 703 /**< Remote I/O error */
#define SXS_ENOMEDIUM 704 /**< No medium found */
#define SXS_EMEDIUMTYPE 705 /**< Wrong medium type */
#define SXS_ENOKEY 706 /**< Required key not available */
#define SXS_EKEYEXPIRED 707 /**< Key has expired */
#define SXS_EKEYREVOKED 708 /**< Key has been revoked */
#define SXS_EKEYREJECTED 709 /**< Key was rejected by service */
#define SXS_UNIX_ERRMAP_SIZE 42
#ifndef WIN32
#ifndef __APPLE__
extern sxs_int32_t sxs_unix_errmap[SXS_UNIX_ERRMAP_SIZE];
#endif
#endif

#define SXS_UNIX_HERR_START 1001
#define SXS_UNIX_HERR_END 1332
#define SXS_NETDB_INTERNAL 1001 /**< See errno. */
#define SXS_NETDB_SUCCESS 1002 /**< No problem. */
#define SXS_HOST_NOT_FOUND 1003 /**< Authoritative Answer Host not found. */
#define SXS_TRY_AGAIN 1004 /**< Non-Authoritative Host not found, or SERVERFAIL. */
#define SXS_NO_RECOVERY 1005 /**< Non recoverable errors, FORMERR, REFUSED, NOTIMP. */
#define SXS_NO_DATA 1006 /**< Valid name, no data record of requested type. */
#define SXS_UNIX_HERRMAP_SIZE 6
#ifndef WIN32
extern sxs_int32_t sxs_unix_herrmap[SXS_UNIX_HERRMAP_SIZE];
#endif

#define SXS_ERR_START 6001
#define SXS_ERR_END 6332
#define SXS_ERRCONNCLOSED 6001 /**< Connection closed by peer */
#define SXS_ERRALREADYBLOCK 6002 /**< The socket is already blocking */
#define SXS_ERRALREADYNONBLOCK 6003 /**< The socket is already non-blocking */
#define SXS_ERRSETNONBLOCK 6004 /**< Failed to set socket non-blocking/blocking state */
#define SXS_ERRSELECTFAIL 6005 /**< Failed to monitor a socket descriptor */
#define SXS_ERRRECVFAIL 6006 /**< Failed to recv data from socket descriptor */
#define SXS_ERRSENDFAIL 6007 /**< Failed to send data from socket descriptor */
#define SXS_ERRRECVTIMEDOUT 6008 /**< Non-blocking recv timed out */
#define SXS_ERRSENDTIMEDOUT 6009 /**< Non-blocking send timed out */
#define SXS_ERRCONNTIMEDOUT 6010 /**< Non-blocking connect timed out */
#define SXS_ERRGETSOCKOPTFAIL 6011 /**< Failed to get socket option */
#define SXS_ERRSETSOCKOPTFAIL 6012 /**< Failed to set socket option */
#define SXS_ERRCLOSEFAIL 6013 /**< Failed to close socket */
#define SXS_ERRUNEXPECTED 6014 /**< An unexpected path was taken */


#define SXS_UNIXMAC_ERR_START 6333
#define SXS_UNIXMAC_ERR_END 6665
#define SXS_EPERM 6333 /**< Operation not permitted */
#define SXS_ENOENT 6334 /**< No such file or directory */
#define SXS_ESRCH 6335 /**< No such process */
#define SXS_EIO 6336 /**< I/O error */
#define SXS_ENXIO 6337 /**< No such device or address */
#define SXS_E2BIG 6338 /**< Argument list too long */
#define SXS_ENOEXEC 6339 /**< Exec format error */
#define SXS_ECHILD 6340 /**< No child processes */
#define SXS_ENOMEM 6341 /**< Out of memory */
#define SXS_ENOTBLK 6342 /**< Block device required */
#define SXS_EBUSY 6343 /**< Device or resource busy */
#define SXS_EEXIST 6344 /**< File exists */
#define SXS_EXDEV 6345 /**< Cross-device link */
#define SXS_ENODEV 6346 /**< No such device */
#define SXS_ENOTDIR 6347 /**< Not a directory */
#define SXS_EISDIR 6348 /**< Is a directory */
#define SXS_ENFILE 6349 /**< File table overflow */
#define SXS_ENOTTY 6350 /**< Not a typewriter */
#define SXS_ETXTBSY 6351 /**< Text file busy */
#define SXS_EFBIG 6352 /**< File too large */
#define SXS_ENOSPC 6353 /**< No space left on device */
#define SXS_ESPIPE 6354 /**< Illegal seek */
#define SXS_EROFS 6355 /**< Read-only file system */
#define SXS_EMLINK 6356 /**< Too many links */
#define SXS_EPIPE 6357 /**< Broken pipe */
#define SXS_EDOM 6358 /**< Math argument out of domain of func */
#define SXS_ERANGE 6359 /**< Math result not representable */
#define SXS_EDEADLK 6360 /**< Resource deadlock would occur */
#define SXS_ENOLCK 6361 /**< No record locks available */
#define SXS_ENOSYS 6362 /**< Function not implemented */
#define SXS_ENOMSG 6363 /**< No message of desired type */
#define SXS_EIDRM 6364 /**< Identifier removed */
#define SXS_ENOSTR 6365 /**< Device not a stream */
#define SXS_ENODATA 6366 /**< No data available */
#define SXS_ETIME 6367 /**< Timer expired */
#define SXS_ENOSR 6368 /**< Out of streams resources */
#define SXS_ENOLINK 6369 /**< Link has been severed */
#define SXS_EPROTO 6370 /**< Protocol error */
#define SXS_EMULTIHOP 6371 /**< Multiphop attempted */
#define SXS_EBADMSG 6372 /**< Not a data message */
#define SXS_EOVERFLOW 6373 /**< Value too large for defined data type */
#define SXS_EILSEQ 6374 /**< Illegal byte sequence */
#define SXS_ECANCELED 6375 /**< Operation Canceled */
#define SXS_UNIXMAC_ERRMAP_SIZE 43
#ifndef WIN32
extern sxs_int32_t sxs_unixmac_errmap[SXS_UNIXMAC_ERRMAP_SIZE];
#endif



#define SXS_MAC_ERR_START 6666
#define SXS_MAC_ERR_END 6998
#define SXS_EBADRPC 6666 /**< RPC struct is bad */
#define SXS_ERPCMISMATCH 6667 /**< RPC version wrong */
#define SXS_EPROGUNAVAIL 6668 /**< RPC prog not avail */
#define SXS_EPROGMISMATCH 6669 /**< Program version wrong */
#define SXS_EPROCUNAVAIL 6670 /**< Bad procedure for program */
#define SXS_EFTYPE 6671 /**< Inaappropriate file type or format */
#define SXS_EAUTH 6672 /**< Authentication error */
#define SXS_ENEEDAUTH 6673 /**< Need authenticator */
#define SXS_EPWROFF 6674 /**< Device power is off */
#define SXS_EDEVERR 6675 /**< Device error, e.g. paper out */
#define SXS_EBADEXEC 6676 /**< Bad executable */
#define SXS_EBADARCH 6677 /**< Bad CPU type in executable */
#define SXS_ESHLIBVERS 6678 /**< Shared library version mismatch */
#define SXS_EBADMACHO 6679 /**< Malformed Macho file */
#define SXS_ENOATTR 6680 /**< Attribute not found */
#define SXS_ELAST 6681 /**< Must be equal largest errno */
#define SXS_MAC_ERRMAP_SIZE 16
#ifdef __APPLE__
extern sxs_int32_t sxs_mac_errmap[SXS_MAC_ERRMAP_SIZE];
#endif

#endif
