INT_SVN_SERV="192.168.11.3"
EXT_SVN_SERV="extsvn.cyph.org:8000"
SVN_SERV_PROJ_PATH="/private/pmf_server/trunk"
URL_LEADIN="https://"

INT_URL=${URL_LEADIN}${INT_SVN_SERV}${SVN_SERV_PROJ_PATH}
EXT_URL=${URL_LEADIN}${EXT_SVN_SERV}${SVN_SERV_PROJ_PATH}